#!/usr/bin/env bash

# Script to batch process MKV files using mkvtoolnix.
# Requires options file generated by mkvtoolnix in the
# same directory as the video files.
# Usage: script.sh options.json

set -euo pipefail
shopt -s nullglob nocaseglob

# ANSI colours
readonly GREEN="\033[32m"
readonly RED="\033[31m"
readonly BLUE="\033[34m"
readonly RESET="\033[0m"

# Check dependencies
for cmd in mkvmerge mkvpropedit jd; do
    if ! command -v $cmd &> /dev/null; then
        printf "${RED}Error: %s not found in PATH.${RESET}\n" "$cmd"
        exit 1
    fi
done

# Validate arguments
if [[ "$#" -eq 0 || ! "$1" =~ \.json$ ]]; then
    printf "%sError: No or invalid options file provided.%s\n" "$RED" "$RESET" >&2
    printf "Usage: source/%s [options].json\n" "$(basename "$0")"
    exit 1
fi

# Get directory path
opt_file="$(realpath "$1")"

if [[ ! -f "$opt_file" ]]; then
    printf "%sError: Options file not found: %s%s\n" "$RED" "$1" "$RESET" >&2
    exit 1
fi

cd "$(dirname "$opt_file")"

# Filter JSON file
filtered_opt=$(jq '
  # First pass: remove --output and next element
  [foreach .[] as $item (
    {prev: null, skip: false};
    if .skip then
      {prev: $item, skip: false}
    elif $item == "--output" then
      {prev: $item, skip: true}
    else
      {prev: $item, skip: false, emit: $item}
    end;
    select(has("emit")).emit
  )]
  # Second pass: remove content between ( and )
  | [foreach .[] as $item (
    {inside: false};
    if $item == "(" then
      {inside: true}
    elif $item == ")" then
      {inside: false}
    elif .inside then
      {inside: true}
    else
      {inside: false, emit: $item}
    end;
    select(has("emit")).emit
  )]
' "$opt_file")

if [[ -z "$filtered_opt" || "$filtered_opt" == "null" ]]; then
    printf "%sError: Failed to parse JSON options file.%s\n" "$RED" "$RESET" >&2
    exit 1
fi

# Create a temporary filtered options file
temp_opt=$(mktemp)
printf "%s\n" "$filtered_opt" > "$temp_opt"
trap 'rm -f "$temp_opt"' EXIT INT TERM

# Set mkvpropedit options
mkvpe_opt=(--delete title --delete date --set muxing-application="" --set writing-application="")

# Collect files into array
mapfile -d '' video_files < <(find . -maxdepth 1 -type f \( -iname "*.mp4" -o -iname "*.mkv" -o -iname "*.webm" \) -print0)

if [[ ${#video_files[@]} -eq 0 ]]; then
    printf "%sNo video files found in the provided directory.%s\n" "$RED" "$RESET" >&2
    exit 1
fi

# Process video files
for v in "${video_files[@]}"; do
    file_name="$(basename "${v%.*}")"
    output_dir="$(dirname "$v")/mkv_output"
    mkdir -p "$output_dir"
    output="$output_dir/${file_name}.mkv"
    if [[ -f "$output" ]]; then
        printf "Skipping: %s%s%s already exists.\n" "$BLUE" "$(basename "$output")" "$RESET"
        continue
    fi
    if ! mkvmerge @"$temp_opt" -o "$output" "$v"; then
        printf "%sError processing file: %s%s\n" "$RED" "$(basename "$v")" "$RESET" >&2
        exit 1
    fi
    if ! mkvpropedit "$output" "${mkvpe_opt[@]}"; then
        printf "%sError removing metadata from file: %s%s\n" "$RED" "$(basename "$v")" "$RESET" >&2
        exit 1
    fi
done

printf "\n%sAll %d files processed successfully.%s\n" "$GREEN" "${#video_files[@]}" "$RESET"